# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hPtn70VSeMRWDfTdTfumYMXOzrJ31I6a
"""

#pip install streamlit

import streamlit as st
import pandas as pd
import joblib
import numpy as np

# ======================
# Cargar modelo
# ======================
model = joblib.load('modelo_churn.pkl')

# Si usaste scaler
# scaler = joblib.load('scaler.pkl')

st.set_page_config(page_title="Predicción de Churn", layout="centered")

st.title("📉 Predicción de Churn de Clientes")
st.write("Ingrese los datos del cliente para estimar la probabilidad de churn.")

# ======================
# Inputs del usuario
# ======================
Tamano_cuenta = st.number_input("Tamaño de cuenta", min_value=0)
Plan_Inter = st.selectbox("Plan de Internet", [0, 1])
Plan_Voz = st.selectbox("Plan de Voz", [0, 1])
Num_Mensajes = st.number_input("Número de mensajes", min_value=0)
Total_min_dia = st.number_input("Minutos día", min_value=0.0)
Total_llama_dia = st.number_input("Llamadas día", min_value=0)
Reclamos = st.number_input("Número de reclamos", min_value=0)

# ======================
# Botón de predicción
# ======================
if st.button("🔍 Predecir churn"):

    X_new = pd.DataFrame([{
        "Tamano_cuenta": Tamano_cuenta,
        "Plan_Inter": Plan_Inter,
        "Plan_Voz": Plan_Voz,
        "Num_Mensajes": Num_Mensajes,
        "Total_min_dia": Total_min_dia,
        "Total_llama_dia": Total_llama_dia,
        "Reclamos": Reclamos
    }])

    # Si usaste scaler
    # X_new = scaler.transform(X_new)

    proba = model.predict_proba(X_new)[0][1]
    pred = int(proba >= 0.3)  # umbral recomendado para churn

    st.subheader("📊 Resultado")

    st.metric("Probabilidad de churn", f"{proba:.2%}")

    if pred == 1:
        st.error("⚠️ Cliente con ALTO riesgo de churn")
    else:
        st.success("✅ Cliente con BAJO riesgo de churn")

